name: Deploy Staging

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: staging
        env:
            PROJECT_ROOT: /home/ubuntu/data/portal-frontend
            COMPOSE_FILE: docker-compose.yml
            ENV_FILE: /home/ubuntu/data/env/portal-frontend/staging.env
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            - name: Copy code to EC2
              run: |
                  rsync -avz --delete \
                    -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
                    --exclude='.git' \
                    --exclude='.next' \
                    --exclude='node_modules' \
                    --exclude='.env*' \
                    --exclude='.idea' \
                    ./ ubuntu@13.219.176.11:${{ env.PROJECT_ROOT }}

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME || 'ubuntu'}}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: ${{ secrets.EC2_PORT || '22' }}
                  script: |
                      set -a
                      source ${{ env.ENV_FILE }}
                      cd ${{ env.PROJECT_ROOT }}
                      docker compose -f ${{ env.COMPOSE_FILE }} build --no-cache
                      docker compose -f ${{ env.COMPOSE_FILE }} up -d --remove-orphans --force-recreate
                      docker compose -f ${{ env.COMPOSE_FILE }} ps
