AWSTemplateFormatVersion: '2010-09-09'
Description: 'State: Container registry repo for services'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Repository Configuration'
      Parameters:
      - RepositoryName
Parameters:
  RepositoryName:
    Description: 'Name of the ECR repository.'
    Type: String
Resources:
  Repository:
    Type: 'AWS::ECR::Repository'
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 1,
              "description": "Only keep 5 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 5
              },
              "action": { "type": "expire" }
            }]
          }
      RepositoryName: !Ref RepositoryName
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
